# Generated by Django 5.2.1 on 2025-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='solve_number',
            field=models.SmallIntegerField(db_index=True, default=6),
            preserve_default=False,
        ),
    ]
