# Generated by Django 5.1.8 on 2025-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_solve_solve_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='official',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
