# Generated by Django 5.2.1 on 2025-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_type',
            field=models.CharField(default='average', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ranking_format',
            field=models.CharField(default='average', max_length=255),
            preserve_default=False,
        ),
    ]
