# Generated by Django 5.1.8 on 2025-07-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_event_average_type_event_ranking_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="school_id",
            field=models.CharField(db_index=True, default="hello", max_length=255),
            preserve_default=False,
        ),
    ]
