# Generated by Django 5.2.1 on 2026-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitor_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='official_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
